<a href="https://colab.research.google.com/github/Aniketyadav29/Data-Science-Tutorial/blob/main/Module_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Module -1 Python Basics**

1.varriables

In [ ]:
# Variable:-

x=5
y=7
print(x)
print(y)
name="Aniket Yadav"
print(name)

a=3
b=3.14
z="Hiii"
print(a)
print(b)
print(z)

5
7
Aniket Yadav
3
3.14
Hiii
5
7
Aniket Yadav
3
3.14
Hiii


2.Dynamic Typing

In [ ]:
y=10
x="Aniket Yadav"
z=3.24
print(type(y))
print(type(x))
print(type(z))

<class 'int'>
<class 'str'>
<class 'float'>


3.Assigining Same Value

In [ ]:
a=b=c=100
print(a,b,c)

100 100 100


4. Assignning Different Vlaues

In [ ]:
x,y,z=1,2.5,"Python"
print(x,y,z)

1 2.5 Python


**Data Type**

1.Integer


In [ ]:
age=25
print(type(age))

<class 'int'>


2.Float

In [ ]:
price=99.99
print(type(price))

<class 'float'>


3.complex

In [ ]:
x=3+4j
print(x)
print(type(x))

(3+4j)
<class 'complex'>


**Sequence in Data Tpyes**

1.List

In [ ]:
a=[1,2,3,5,6,7,8]
print(a)
print(type(a))

[1, 2, 3, 5, 6, 7, 8]
<class 'list'>


2.Tuples

In [ ]:
t1=(1,)
print(type(t1))

t2=('BBD','BBD','BBD','BBD',1,3)
print(t1)
print(t2)

<class 'tuple'>
(1,)
('BBD', 'BBD', 'BBD', 'BBD', 1, 3)


**Set Data Type**

set

In [ ]:
s1={"a","a","b","b","c","d"}
print(s1)
s2={"BBD","BBD","FOR","BBD"}
for i in s2:
  print(i)

{'c', 'b', 'a', 'd'}
FOR
BBD


**Dictionary Data Type**

In [ ]:
d={1:"BBD",2:"FOR",3:"BBD"}

print(d[1])

print(d.get(2))
print(d.get(3))


BBD
FOR
BBD


#**Operator**

1.Arithmetic Operator

Arithmetic operator are used to perform basic mathematical operations like , addition , substraction , multiplication and division .

In [ ]:
a=5
b=2
print("Addition",a+b)
print("Substraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Modulus",a%b)
print("Exponantial",a**b)
print(a//b)

Addition 7
Substraction 3
Multiplication 10
Division 2.5
Modulus 1
Exponantial 25
2


2.Comparision Operator

comparision operator or Relational Operator campares values. It either returns True or False accrding to the condition.

In [ ]:
a=13
b=33
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

False
True
False
True
False
True


3.Logical Operator

Logical operator performs logical AND, Logical NOT , Logical OR operations. it is used to combine conditional statements.

The precedence of Logical Operator in Python is as follows:

1. Logical Not
2. Logical And
3. Logical Or

In [ ]:
age=20
if age>=18 and age <=70:
  print("You are eligible for voting")
else:
  print("You are not eligible for voting")

You are eligible for voting


4.Bitwise Operator

A bitwise operator is an operator that performs operations directly on the binary (bit) representation of integers. It manipulates individual bits (0s and 1s) of a number.


In [ ]:
a=4
b=10
print(~a)
print(a<<b)
print(a&b)
print(a^b)
print(a|b)
print(a>>b)


-5
4096
0
14
14
0


5.Assignment operator

An assignment operator is used to assign a value to a variable.
this operator is used to assign the value of the right side of the expression and left side of the operand .

In [ ]:
a=10
b=a
print(b)
b+=a
print(b)
b-=a
print(b)
b*=a
print(b)
b<<=a
print(b)


10
20
10
100
102400


6.Identity OPerator

An identity operator is used to check whether two variables refer to the same object in memory

| Operator | Meaning                                                     |
| -------- | ----------------------------------------------------------- |
| `is`     | Returns `True` if both variables refer to the same object   |
| `is not` | Returns `True` if both variables refer to different objects |


In [ ]:
a=10
b=20
c=a
print(a is not b)
print(a is c )

True
True


7.Membership operator

A membership operator is used to check whether a value exists in a sequence such as a string, list, tuple, or set.

| Operator | Meaning                                                    |
| -------- | ---------------------------------------------------------- |
| `in`     | Returns `True` if the value is present in the sequence     |
| `not in` | Returns `True` if the value is not present in the sequence |


In [ ]:
x=24
y=20
my_list=[10,20,30,40,50,60]
if (x not in my_list):
  print("x is NOT present in the given list")
else:
  print("x is present in the given list")

if (y in my_list):
  print("y is present in the given list")
else:
  print("y is NOT present in the given list")

x is NOT present in the given list
y is present in the given list


8.Ternary Operator

A ternary operator is a shorthand way of writing an if-else statement in a single line. It evaluates a condition and returns one of two values based on whether the condition is True or False.



In [ ]:
age = 18

result = "Adult" if age >= 18 else "Minor"
print(result)  # Adult

a,b=10,20
min = a if a<b else b
print(min)

Adult
10


Que.1

In [ ]:
a=int(input(" Enter the first number"))
b=int(input(" Enter the second number"))
print("Addition", a+b)
print("Substraction", a-b)
print("Multiplication", a*b)
print("Division", a/b)
print("Modulus", a%b)
print("Exponantial", a**b)

Enter the first number29
Enter the second number23
Addition 52
Substraction 6
Multiplication 667
Division 1.2608695652173914
Modulus 6
Exponantial 4316720717749415770740818372739989


Que.2

In [ ]:
catalog=["b.tech" , "b.phrama" , "b.com", "bca"]
if ("b.tech" in catalog):
  print("Yes")
else:
  print("No")

Yes


Que.3

In [ ]:
username="Aniket@1235"
passward =123456
username=str(input("Enter Your Username "))
password=int(input("Enter you password"))

if(username=="Aniket@1235" and password==123456):
  print("Login Successful")
else:
  print("Login Failed")

Enter Your Username Aniket@1235
Enter you password123456
Login Successful


Que.4

In [ ]:
salary=float(input("Enter your salary:"))
experience=float(input("Enter your experience:"))
if(salary>30000 and experience>2 ):
  print("Eligible for Bonus")

else:
  print("Not Eligible for Bonus")

Enter your salary:1200000
Enter your experience:3
Eligible for Bonus


#**Conditional Statements**

1.If Statement

An if statement is a conditional statement that executes a block of code only when a specified condition is True.

In [ ]:
age=19
if age>18:
  print("Eligible for Voting .")

Eligible for Voting .


2.If else Statement

If else statement is used to execute one block of code when the condition is true and another block the condition is false.

In [ ]:
a=10
if age<=12:
  print("Travel for free.")
else:
  print("Pay for ticket.")

Pay for ticket.


3.if-elif-else Statement

elif condition is used to check multiple condition in a program . it executes a block of code when its condition evaluates to True after previous conditions evaluates to False .

In [ ]:
age=25
if age<=12:
  print("Child")
elif age<=26:
  print("Teenager")
elif age<=30:
  print("Young Adult")
elif age<=60:
  print("Adult")
else:
  print("Senior Citizen")

Teenager


4.Nested If Else Condition

Nester If Else Condition is an is-else statement placed inside another if or else block. it is used to check condition within another condition .

In [ ]:
age=70
is_member=True
if age >=60:
  if is_member:
    print("30% Senior discount!")
  else:
    print("20% senior discount.")
else:
  print("Not eligible for a senior discount.")

30% Senior discount!


#**Loops**

1.For Loop

A for loop iterates over a sequence (list ,tuple ,set etc.)

In [ ]:
for i in range(1,6):
  print(i)


1
2
3
4
5


Example:-

In [ ]:
fruits=["Apple","Banana","Kela", "Mango","Litchi"]
for fruit in fruits:
  print(fruit)

Apple
Banana
Kela
Mango
Litchi


2.While Loop

A while loop runs as a condition is True .

In [ ]:
count=1
while count<=5:
  print(count)
  count +=1

1
2
3
4
5


**3.Loop Control Statement**

A.Break

stops the loops immedietely .

In [ ]:
for i in range (1,10):
  if i==5:
    break
  print(i)

1
2
3
4


B.Continue

Skips the current iteration

In [ ]:
for i in range (1,6):
  if i==3:
    continue
  print(i)

1
2
4
5


C.Pass

placehonder statements

In [ ]:
for i in range (5):
  pass

print("Loop completed ")

Loop completed 


4.Nested Loops

A loop inside another loop.

In [ ]:
for i in range(1,4):
  for j in range(1,4):
    print(i,j)

1 1
1 2
1 3
2 1
2 2
2 3
3 1
3 2
3 3


**Important Question**

Que 1.

In [ ]:
n = int(input("Enter a number: "))

sum_numbers = 0

for i in range(1, n + 1):
    sum_numbers += i

print("Sum of numbers from 1 to", n, "is:", sum_numbers)

Enter a number: 5
Sum of numbers from 1 to 5 is: 15


Que 2.

In [ ]:
password=1234532
password=int(input("Enter your password"))
if(password==123456):
  print("Login Successful")
else:
  print("Login Failed")

Enter your password13241
Login Failed


Que 3.

In [ ]:
numbers = [10, -5, 7, -2, 0, 15, 8, -1]

count = 0

for num in numbers:
    if num > 0:
        count += 1

print("Number of positive numbers:", count)

Number of positive numbers: 4


Que 4.

In [ ]:
monthly_target=300
mt=int(input("Enter your mt :"))
if (mt>monthly_target):
  print("Target Achived ")
else:

  print("Target is not Achived.")

Enter your mt :4233
Target Achived 


Que 5.

In [ ]:
count=0
for i in range(1,51):
  if i%2==0:
    count +=1
print("All Even Numbers between 1 to 51 :",count)

All Even Numbers between 1 to 51 : 25


Another Method :

In [ ]:
count=0
for i in range(2,51,2):
    print(i)
    count+=1
print("Total Even Numbers are :",count)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
Total Even Numbers are : 25


#**Function**

fuction is block of code that performs a specific tasks.

types of funtion :

1.Built-In-Fuction.

2.User Define Fuction.

1. Built in function:

length()

type()

reange()

In [ ]:
def greet():
    print("Welcome to BBD.")
greet()

Welcome to BBD.


2. Function with Parameter

In [ ]:
def Aniket():
  print("Aniket is hero")
Aniket()

Aniket is hero


In [ ]:
def Aniket(name):
  print("Hello",name)
Aniket("Suraj")

Hello Suraj


3.Function with Multiple Parameter

In [ ]:
def add(a,b):
  print(a+b)
add(1222332322,133456432)


1355788754


4.Function with Return Statement

return sends a value  ack ti the caller .

In [ ]:
def square(num):
  return num*num
result=square(5)
print(result)

25


5.Default parameter



In [ ]:
def country(name="India"):
  print("Country:",name)
country()
country("USA")

Country: India
Country: USA


6.Keyword Arguments:


In [ ]:
def student(name,age):
  print(name,age)
student(age=22,name="Shivam")

Shivam 22


7.Variable Length Argument(*args)

used when the number of arguments is unknown .


In [ ]:
def total (*Numbers):
  print(sum(Numbers))

total(1,2,3,4,5)


15


8.Keyword Varriable Argumemts(**kwargs)

In [ ]:
def info(**details):
  print(details)
info(name="Shivam",city="Delhi")


{'name': 'Shivam', 'city': 'Delhi'}


9.Lemda Function

small anonymous Function.

In [ ]:
square=lambda x:x*x
print(square(6))


36


10.Function with Lists

In [ ]:
def average(numbers):
  return sum(numbers)/len(numbers)
my_list=[10,20,30,40,50]
result=average(my_list)
print(result)

30.0


Que.1


Employee Salary Calculator

In [ ]:

def calc_final_salary(salary,bonus,tax):
  final_salary=salary+bonus-tax
  return final_salary

salary=float(input("Enter your salary:"))
bonus=float(input("Enter your bonus:"))
tax=float(input("Enter your tax:"))
final_salary=calc_final_salary(salary,bonus,tax)
print("Final Salary:",final_salary)



Enter your salary:2335533
Enter your bonus:223324
Enter your tax:132334
Final Salary: 2426523.0


Que 2.

Student Result Analysis System

In [ ]:
def calculate_result(*marks):
    total = sum(marks)
    average = total / len(marks)

    if average >= 90:
        grade = "A+"
    elif average >= 80:
        grade = "A"
    elif average >= 70:
        grade = "B"
    elif average >= 60:
        grade = "C"
    elif average >= 50:
        grade = "D"
    else:
        grade = "F"

    print("Total Marks:", total)
    print("Average Marks:", average)
    print("Grade:", grade)

calculate_result(85, 90, 78, 88, 92)

Total Marks: 433
Average Marks: 86.6
Grade: A


Que 3.

Customer Information Management System

In [ ]:
def customer_details(**kwargs):
    print("Customer Details:")
    for key, value in kwargs.items():
        print(key, ":", value)
customer_details(
    Name="Aniket",
    Age=21,
    City="Lucknow",
    Email="aniket@gmail.com",
    Phone="9876543210"
)

Customer Details:
Name : Aniket
Age : 21
City : Lucknow
Email : aniket@gmail.com
Phone : 9876543210


# **File Handling**

1.Opening a File

In [1]:
# file=open("/content/input.txt","r",encoding="latin-1")
# print(file.read())
# file.close()

2.Reading a File

In [2]:
# file=open("input.txt","r")
# content=file.read()
# print(content)
# file.close()

**readline()**

reads line by line .

In [ ]:
file=open("/content/input.txt","r")
line1=file.readline()
line2=file.readline()
print(line1)
print(line2)

file.close()

First Citizen:

Before we proceed any further, hear me speak.



**writing a file**

Creates anew file or overwrites existing content .

In [ ]:
file=open("Student.txt","w")
file.write("Name:Shivam\n")
file.write("Age:22\n")
file.write("City:Delhi\n")
file.close()
print("Data Written Successfully.")

Data Written Successfully.


construtor (init Method)

A construtors automatically runs when an object is created

In [ ]:
class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

student1 = Student("Shivam", 22)

print("Name:", student1.name)
print("Age:", student1.age)

Name: Shivam
Age: 22


4. Instance Variable

Variables belonging to each object

In [ ]:
class Student:
    def __init__(self, name, age, marks):
        self.name = name
        self.age = age
        self.marks = marks

    def display(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Marks:", self.marks)

# Creating an object
student1 = Student("Shivam", 22, 95)

# Calling the display method
student1.display()

Name: Shivam
Age: 22
Marks: 95


**Inheritance**

Inheritance is an OOP concept in which a child class acquires the properities (attributes ) and behaviour (methods) of an existing parent class .

In [ ]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return "Some generic animal sound"

class Dog(Animal):
    def speak(self):
        return f"{self.name} says Woof!"

class Cat(Animal):
    def speak(self):
        return f"{self.name} says Meow!"


my_dog = Dog("Buddy")
my_cat = Cat("Whiskers")

print(my_dog.speak())
print(my_cat.speak())

Buddy says Woof!
Whiskers says Meow!


**Polymorphisms**

Polymorphism translates to "many forms." In Object-Oriented Programming, it means that a single action or method can behave differently depending on the exact object that is performing it

In [ ]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        return "Some generic animal sound"

class Dog(Animal):
    def speak(self):
        return f"{self.name} says Woof!"

class Cat(Animal):
    def speak(self):
        return f"{self.name} says Meow!"

class Cow(Animal):
    def speak(self):
        return f"{self.name} says Moo!"


my_animals = [Dog("Buddy"), Cat("Whiskers"), Cow("Bessie")]

for animal in my_animals:
    print(animal.speak())

**Abstraction**

Abstraction is the concept of hiding complex implementation details and showing only the essential features to the user. In Object-Oriented Programming, it acts as a strict blueprint

In [ ]:
from abc import ABC, abstractmethod
import math

class Shape(ABC):
    @abstractmethod
    def area(self):
        pass

    @abstractmethod
    def perimeter(self):
        pass

class Square(Shape):
    def __init__(self, side):
        self.side = side

    def area(self):
        return self.side * self.side

    def perimeter(self):
        return 4 * self.side

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return math.pi * (self.radius ** 2)

    def perimeter(self):
        return 2 * math.pi * self.radius


my_square = Square(4)
my_circle = Circle(3)

print(my_square.area())
print(my_circle.area())

16
28.274333882308138


# Numpy

NumPy

NumPy (Numerical Python) is a powerful python library used for:

1.Numerical Computation

2.Working with arrays and matrices

3.Mathematical Operation

4.Data Science and Machine Learning

In [ ]:
pip install numpy


Import NumPy

In [ ]:
import numpy as np


# Arrays

An array is a fundamental data structure used in computer programming to store a collection of related items (like numbers, words, or objects) inside a single variab

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


**one-dimensional (1D)**

array is the simplest type of array. You can think of it as a single, straight line of data—like a single row of lockers, a grocery list, or a line of people waiting for a bus.

In [ ]:
import numpy as np

# -----------------------------------------
# 1. Creating a 1D NumPy Array
# -----------------------------------------
# We pass a standard Python list into np.array()
numbers = np.array([10, 20, 30, 40, 50])

print("The 1D Array:")
print(numbers)

# To access a specific element, you still use the zero-based index
print("\nThe first element is:", numbers[0])
print("The third element is:", numbers[2])

# -----------------------------------------
# 2. Why NumPy Arrays are Powerful
# -----------------------------------------
# If you tried to multiply a standard Python list by 2,
# it would just duplicate the list items.
# With a NumPy array, it does the math on every single item instantly!

multiplied_array = numbers * 2

print("\nThe Array multiplied by 2:")
print(multiplied_array)
# Output: [20 40 60 80 100]

The 1D Array:
[10 20 30 40 50]

The first element is: 10
The third element is: 30

The Array multiplied by 2:
[ 20  40  60  80 100]


**2D Array:**

If a 1-Dimensional array is a single row of lockers, a 2-Dimensional (2D) array is the entire wall of lockers.

It is essentially a grid or a table with rows (horizontal) and columns (vertical). Think of a standard Excel spreadsheet or a chessboard.

In [ ]:
import numpy as np

# A 2D array (3 rows, 4 columns)
grid = np.array([
    [10, 20, 30, 40],  # Row 0
    [50, 60, 70, 80],  # Row 1
    [90, 100, 110, 120] # Row 2
])

print("The whole grid:")
print(grid)

# To get the number 70 (which is in Row 1, Column 2)
print("\nValue at Row 1, Col 2:")
print(grid[1, 2])  # Output: 70

The whole grid:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Value at Row 1, Col 2:
70


**3D array**

To build a 3D array in Python, you create a "list of lists of lists." Notice how we are essentially just stacking two 2D grids together.

In [ ]:
import numpy as np

# A 3D array (2 layers, 3 rows, 3 columns)
cube = np.array([
    # Layer 0 (Depth 0)
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    # Layer 1 (Depth 1)
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

# To get the number 15:
# It is in Layer 1, Row 1, Column 2 (remember, we count from 0!)
print("Value at Layer 1, Row 1, Col 2:")
print(cube[1, 1, 2])  # Output: 15

**Array Attributes**

NumPy array attributes provide important information about an array , such as its dimension ,size , shape, and data type.

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:", arr.shape)
print("Dimension:",arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)

Shape: (2, 3)
Dimension: 2
Size: 6
Data Type: int64


**Special Arrays**

creates an array where every elements is 0.

Zeros Array np.zeros()

creates am array where every element is 0.


In [ ]:
import numpy as np
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**np.empty**

Creates an array without initialization values.

In [ ]:
import numpy as np
arr=np.empty((2,3))
print(arr)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]]


**np.arrange()**

Creates equally spaced values.

In [ ]:
import numpy as np
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


**np.linspace()**

Creates equally spaced numbers between two values .

In [ ]:
import numpy as np
arr=np.random.rand(3,3)
print(arr)

[[0.92820873 0.62889068 0.3466172 ]
 [0.15330631 0.37486657 0.36515003]
 [0.70030887 0.00201508 0.90144157]]


np.random.rand()

Random integers.

In [ ]:
import numpy as np

arr=np.random.randint(1,100,(3,4))
print(arr)

[[21 27 94 60]
 [42 11 52 25]
 [28 28 41 62]]


**np.diag()**

creates a diagonal matrix or extracts diagonal elements .

In [ ]:
import numpy as np
arr=np.diag([5,10,15])
print(arr)

[[ 5  0  0]
 [ 0 10  0]
 [ 0  0 15]]


1.Create a 3x4 NumPy array filled with zeros.

In [ ]:
import numpy as np
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2.Create 4x5 NumPy array filled with ones.

In [ ]:
import numpy as np
arr=np.ones((4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.create 3x3 array using np.empty() and obeserve the values .Explain why the values are nor initialized .

In [ ]:
import numpy as np
arr=np.empty((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


4.Create a 5x5 identity Matrix using NumPy

In [ ]:
import numpy as np
arr=np.eye(5,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


5.Create a 4x4 diagonal matrix with diagonal elements 10,20,30 and 40.

In [ ]:
import numpy as np
arr=np.diag([10,20,30,40])
print(arr)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


6.create a 5x5 array where every elements is 99.

In [ ]:
import numpy as np
arr=np.full((5,5),99)
print(arr)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


7.generate 20 equally spaced number between 1 and 100.

In [ ]:
import numpy as np
arr=np.linspace(1,100,20)
print(arr)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


**(1)ndim(Number of dimension)**

ndim tells us how many dimensions (axes) an array has.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.ndim)

1


In [ ]:
arr=np.array([
    [
        [1,2,3],
        [4,5,6]
    ]

])
print(arr.ndim)

3


**(2)Shape**

shape tells us how many rows and coloums are present .

In [ ]:
import numpy as np
arr=np.array([[10,20,30],
             [40,50,60]])
print(arr.shape)

(2, 3)


In [ ]:
arr=np.array([
    [
        [1,2],
        [3,4]
    ]
])
print(arr)

[[[1 2]
  [3 4]]]


**3.Size**

size means total no.of elements formula = Rows*colums.

In [ ]:
arr=np.array([
    [10,20,30],
    [40,50,60]
])
print(arr.size)

6


**4.dtype**

dtype means data type of every elements .

In [ ]:
import numpy as np
arr=np.array([10,20,30])
print(arr.dtype)

int64


**Indexing**

Indexing means accessing a single element from an array using its position (index).

In [ ]:
import numpy as np

# Create a 1D array
arr_1d = np.array([10, 20, 30, 40, 50])

# Basic Indexing
print(arr_1d[0])    # Output: 10 (First element)
print(arr_1d[-1])   # Output: 50 (Last element)

# Slicing
print(arr_1d[1:4])  # Output: [20 30 40] (Index 1 up to, but not including, 4)
print(arr_1d[::2])  # Output: [10 30 50] (Every second element)

Slicing

In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])

print(arr[1:5])
print(arr[:4])
print(arr[3:])
print(arr[:])

[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 20 30 40 50 60 70]


Reverse Slicing

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[::-1])



[50 40 30 20 10]


2D Slicing

In [ ]:
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[0,:])
print(arr[1,:])
print(arr[2,:])
print(arr[:,0])
print(arr[:,1])
print(arr[:,2])

[10 20 30]
[40 50 60]
[70 80 90]
[10 40 70]
[20 50 80]
[30 60 90]


Slicing in 3D Array

In [ ]:
import numpy as np

arr

Q.1

In [ ]:
import numpy as np
arr = np.arange(10, 101, 10)

print("Array:", arr )
print("First elemnt:", arr[0])
print("Third element:", arr[2])
print("Last element:", arr[-1])


Array: [ 10  20  30  40  50  60  70  80  90 100]
First elemnt: 10
Third element: 30
Last element: 100


Q.2

In [ ]:
import numpy as np
arr = np.arange(1, 21)

print("Array:", arr)
print("Element from index 5 to index 12:", arr[5:13])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Element from index 5 to index 12: [ 6  7  8  9 10 11 12 13]


Q.3

In [ ]:
import numpy as np
arr = np.arange(1,16)

print("Array:", arr)
print("Every second element: ", arr[::2])

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Every second element:  [ 1  3  5  7  9 11 13 15]


Q.4


In [ ]:
import numpy as np
arr = np.arange(1, 21)
print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reversed Array: [20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


Q.5

In [ ]:
import numpy as np
arr = np.arange(1,17).reshape(4,4)

print("Original Array:")
print(arr)

print("\nMiddle 2*2 Subarray: ")
print(arr[1:3, 1:3])

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Middle 2*2 Subarray: 
[[ 6  7]
 [10 11]]


Q.6

In [ ]:
import numpy as np
arr = np.arange(1,26).reshape(5,5)

print("Origianl Array:")
print(arr)

print("\nLast 2 Row:")
print(arr[-2:,:])

print("\nFirst 3 Column:")
print(arr[:,:3])

print("\nLast 3 Column:")
print(arr[:,-3:])

print("\nBottom-right 3*3 Subarray:")
print(arr[-3:,-3:])

Origianl Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Last 2 Row:
[[16 17 18 19 20]
 [21 22 23 24 25]]

First 3 Column:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]]

Last 3 Column:
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]
 [23 24 25]]

Bottom-right 3*3 Subarray:
[[13 14 15]
 [18 19 20]
 [23 24 25]]


Q.7


In [ ]:
import numpy as np

arr = np.arange(1,21).reshape(4,5)

print("Original Array:")
print(arr)

print("\nAlternate Rows:")
print(arr[::2, :])

print("\nAlternate Columns :")
print(arr[:, ::2])

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Alternate Rows:
[[ 1  2  3  4  5]
 [11 12 13 14 15]]

Alternate Columns :
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]]


Q.8

In [ ]:
import numpy as np
arr = np.arange(1,37).reshape(6,6)

print("Original Array:")
print(arr)

print("\nDiagonal Elements:")
print(np.diag(arr))

print("\nEvery Second Column:")
print(arr[::2, :])

print("\nCenter 4*4 Subarray:")
print(arr[1:5, 1:5])

Original Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Diagonal Elements:
[ 1  8 15 22 29 36]

Every Second Column:
[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]]

Center 4*4 Subarray:
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


# **complete**